// Generated by `wit-bindgen` 0.51.0. DO NOT EDIT!
#ifndef __CPP_GUEST_BINDINGS_WORLD1_CONSUMER_H
#define __CPP_GUEST_BINDINGS_WORLD1_CONSUMER_H
#include <cstdint>
#include <utility>
#include <string_view>
#include <expected>
#include <optional>
#include <cassert>
#include <variant>
#include <tuple>
#include "wit.h"
namespace mydefined {
  namespace package3hl16smu1p {
    namespace itf0_tmmdqdfhit {
      class Handle;
      class Handle : public wit::ResourceImportBase{

        public:

        ~Handle();
        Handle(std::string_view path);
        void Append(std::string_view data) const;
        Handle(wit::ResourceImportBase &&);
        Handle(Handle&&) = default;
        Handle& operator=(Handle&&) = default;
      };

      Handle OpenTemp();
    }
  }
}
namespace wasi {
  namespace cli {
    namespace environment {
      wit::vector<std::tuple<wit::string, wit::string>> GetEnvironment();
      wit::vector<wit::string> GetArguments();
      std::optional<wit::string> InitialCwd();
    }
    namespace exit {
      void Exit(std::expected<void, wit::Void> status);
    }
  }
  namespace io {
    namespace error {
      class Error;
      class Error : public wit::ResourceImportBase{

        public:

        ~Error();
        wit::string ToDebugString() const;
        Error(wit::ResourceImportBase &&);
        Error(Error&&) = default;
        Error& operator=(Error&&) = default;
      };

    }
    namespace poll {
      class Pollable;
      class Pollable : public wit::ResourceImportBase{

        public:

        ~Pollable();
        bool Ready() const;
        void Block() const;
        Pollable(wit::ResourceImportBase &&);
        Pollable(Pollable&&) = default;
        Pollable& operator=(Pollable&&) = default;
      };

      wit::vector<uint32_t> Poll(std::span<std::reference_wrapper<const Pollable> const> in);
    }
    namespace streams {
      class InputStream;
      class OutputStream;
      using Error = error::Error;
      using Pollable = poll::Pollable;
      /// An error for input-stream and output-stream operations.
      struct StreamError {
        /// The last operation (a write or flush) failed before completion.
        /// 
        /// More information is available in the `error` payload.
        struct LastOperationFailed { error::Error value; };
        /// The stream is closed: no more input will be accepted by the
        /// stream. A closed output-stream will return this error on all
        /// future operations.
        struct Closed {};
        std::variant<LastOperationFailed, Closed> variants;
      };
      class InputStream : public wit::ResourceImportBase{

        public:

        ~InputStream();
        std::expected<wit::vector<uint8_t>, StreamError> Read(uint64_t len) const;
        std::expected<wit::vector<uint8_t>, StreamError> BlockingRead(uint64_t len) const;
        std::expected<uint64_t, StreamError> Skip(uint64_t len) const;
        std::expected<uint64_t, StreamError> BlockingSkip(uint64_t len) const;
        poll::Pollable Subscribe() const;
        InputStream(wit::ResourceImportBase &&);
        InputStream(InputStream&&) = default;
        InputStream& operator=(InputStream&&) = default;
      };

      class OutputStream : public wit::ResourceImportBase{

        public:

        ~OutputStream();
        std::expected<uint64_t, StreamError> CheckWrite() const;
        std::expected<void, StreamError> Write(std::span<uint8_t const> contents) const;
        std::expected<void, StreamError> BlockingWriteAndFlush(std::span<uint8_t const> contents) const;
        std::expected<void, StreamError> Flush() const;
        std::expected<void, StreamError> BlockingFlush() const;
        poll::Pollable Subscribe() const;
        std::expected<void, StreamError> WriteZeroes(uint64_t len) const;
        std::expected<void, StreamError> BlockingWriteZeroesAndFlush(uint64_t len) const;
        std::expected<uint64_t, StreamError> Splice(std::reference_wrapper<const streams::InputStream> src, uint64_t len) const;
        std::expected<uint64_t, StreamError> BlockingSplice(std::reference_wrapper<const streams::InputStream> src, uint64_t len) const;
        OutputStream(wit::ResourceImportBase &&);
        OutputStream(OutputStream&&) = default;
        OutputStream& operator=(OutputStream&&) = default;
      };

    }
  }
  namespace cli {
    namespace stdin_ {
      using InputStream = io::streams::InputStream;
      io::streams::InputStream GetStdin();
    }
    namespace stdout_ {
      using OutputStream = io::streams::OutputStream;
      io::streams::OutputStream GetStdout();
    }
    namespace stderr_ {
      using OutputStream = io::streams::OutputStream;
      io::streams::OutputStream GetStderr();
    }
    namespace terminal_input {
      class TerminalInput;
      class TerminalInput : public wit::ResourceImportBase{

        public:

        ~TerminalInput();
        TerminalInput(wit::ResourceImportBase &&);
        TerminalInput(TerminalInput&&) = default;
        TerminalInput& operator=(TerminalInput&&) = default;
      };

    }
    namespace terminal_output {
      class TerminalOutput;
      class TerminalOutput : public wit::ResourceImportBase{

        public:

        ~TerminalOutput();
        TerminalOutput(wit::ResourceImportBase &&);
        TerminalOutput(TerminalOutput&&) = default;
        TerminalOutput& operator=(TerminalOutput&&) = default;
      };

    }
    namespace terminal_stdin {
      using TerminalInput = terminal_input::TerminalInput;
      std::optional<terminal_input::TerminalInput> GetTerminalStdin();
    }
    namespace terminal_stdout {
      using TerminalOutput = terminal_output::TerminalOutput;
      std::optional<terminal_output::TerminalOutput> GetTerminalStdout();
    }
    namespace terminal_stderr {
      using TerminalOutput = terminal_output::TerminalOutput;
      std::optional<terminal_output::TerminalOutput> GetTerminalStderr();
    }
  }
  namespace clocks {
    namespace monotonic_clock {
      using Pollable = io::poll::Pollable;
      /// An instant in time, in nanoseconds. An instant is relative to an
      /// unspecified initial value, and can only be compared to instances from
      /// the same monotonic-clock.
      using Instant = uint64_t;
      /// A duration of time, in nanoseconds.
      using Duration = uint64_t;
      uint64_t Now();
      uint64_t Resolution();
      io::poll::Pollable SubscribeInstant(uint64_t when);
      io::poll::Pollable SubscribeDuration(uint64_t when);
    }
    namespace wall_clock {
      /// A time and date in seconds plus nanoseconds.
      struct Datetime {
        uint64_t seconds;
        uint32_t nanoseconds;
      };
      Datetime Now();
      Datetime Resolution();
    }
  }
  namespace filesystem {
    namespace types {
      class Descriptor;
      class DirectoryEntryStream;
      using InputStream = io::streams::InputStream;
      using OutputStream = io::streams::OutputStream;
      using Error = io::error::Error;
      using Datetime = clocks::wall_clock::Datetime;
      /// File size or length of a region within a file.
      using Filesize = uint64_t;
      /// The type of a filesystem object referenced by a descriptor.
      /// 
      /// Note: This was called `filetype` in earlier versions of WASI.
      enum class DescriptorType : uint8_t {
        /// The type of the descriptor or file is unknown or is different from
        /// any of the other types specified.
        kUnknown = 0,
        /// The descriptor refers to a block device inode.
        kBlockDevice = 1,
        /// The descriptor refers to a character device inode.
        kCharacterDevice = 2,
        /// The descriptor refers to a directory inode.
        kDirectory = 3,
        /// The descriptor refers to a named pipe.
        kFifo = 4,
        /// The file refers to a symbolic link inode.
        kSymbolicLink = 5,
        /// The descriptor refers to a regular file inode.
        kRegularFile = 6,
        /// The descriptor refers to a socket.
        kSocket = 7,
      };

      /// Descriptor flags.
      /// 
      /// Note: This was called `fdflags` in earlier versions of WASI.
      enum class DescriptorFlags : uint8_t {
        k_None = 0,
        /// Read mode: Data can be read.
        kRead = (1ULL<<0),
        /// Write mode: Data can be written to.
        kWrite = (1ULL<<1),
        /// Request that writes be performed according to synchronized I/O file
        /// integrity completion. The data stored in the file and the file's
        /// metadata are synchronized. This is similar to `O_SYNC` in POSIX.
        /// 
        /// The precise semantics of this operation have not yet been defined for
        /// WASI. At this time, it should be interpreted as a request, and not a
        /// requirement.
        kFileIntegritySync = (1ULL<<2),
        /// Request that writes be performed according to synchronized I/O data
        /// integrity completion. Only the data stored in the file is
        /// synchronized. This is similar to `O_DSYNC` in POSIX.
        /// 
        /// The precise semantics of this operation have not yet been defined for
        /// WASI. At this time, it should be interpreted as a request, and not a
        /// requirement.
        kDataIntegritySync = (1ULL<<3),
        /// Requests that reads be performed at the same level of integrety
        /// requested for writes. This is similar to `O_RSYNC` in POSIX.
        /// 
        /// The precise semantics of this operation have not yet been defined for
        /// WASI. At this time, it should be interpreted as a request, and not a
        /// requirement.
        kRequestedWriteSync = (1ULL<<4),
        /// Mutating directories mode: Directory contents may be mutated.
        /// 
        /// When this flag is unset on a descriptor, operations using the
        /// descriptor which would create, rename, delete, modify the data or
        /// metadata of filesystem objects, or obtain another handle which
        /// would permit any of those, shall fail with `error-code::read-only` if
        /// they would otherwise succeed.
        /// 
        /// This may only be set on directories.
        kMutateDirectory = (1ULL<<5),
      };
      static inline DescriptorFlags operator|(DescriptorFlags a, DescriptorFlags b) { return DescriptorFlags(uint8_t(a)|uint8_t(b)); }
      static inline DescriptorFlags operator&(DescriptorFlags a, DescriptorFlags b) { return DescriptorFlags(uint8_t(a)&uint8_t(b)); }
      /// Flags determining the method of how paths are resolved.
      enum class PathFlags : uint8_t {
        k_None = 0,
        /// As long as the resolved path corresponds to a symbolic link, it is
        /// expanded.
        kSymlinkFollow = (1ULL<<0),
      };
      static inline PathFlags operator|(PathFlags a, PathFlags b) { return PathFlags(uint8_t(a)|uint8_t(b)); }
      static inline PathFlags operator&(PathFlags a, PathFlags b) { return PathFlags(uint8_t(a)&uint8_t(b)); }
      /// Open flags used by `open-at`.
      enum class OpenFlags : uint8_t {
        k_None = 0,
        /// Create file if it does not exist, similar to `O_CREAT` in POSIX.
        kCreate = (1ULL<<0),
        /// Fail if not a directory, similar to `O_DIRECTORY` in POSIX.
        kDirectory = (1ULL<<1),
        /// Fail if file already exists, similar to `O_EXCL` in POSIX.
        kExclusive = (1ULL<<2),
        /// Truncate file to size 0, similar to `O_TRUNC` in POSIX.
        kTruncate = (1ULL<<3),
      };
      static inline OpenFlags operator|(OpenFlags a, OpenFlags b) { return OpenFlags(uint8_t(a)|uint8_t(b)); }
      static inline OpenFlags operator&(OpenFlags a, OpenFlags b) { return OpenFlags(uint8_t(a)&uint8_t(b)); }
      /// Number of hard links to an inode.
      using LinkCount = uint64_t;
      /// File attributes.
      /// 
      /// Note: This was called `filestat` in earlier versions of WASI.
      struct DescriptorStat {
        /// File type.
        DescriptorType type;
        /// Number of hard links to the file.
        uint64_t link_count;
        /// For regular files, the file size in bytes. For symbolic links, the
        /// length in bytes of the pathname contained in the symbolic link.
        uint64_t size;
        /// Last data access timestamp.
        /// 
        /// If the `option` is none, the platform doesn't maintain an access
        /// timestamp for this file.
        std::optional<clocks::wall_clock::Datetime> data_access_timestamp;
        /// Last data modification timestamp.
        /// 
        /// If the `option` is none, the platform doesn't maintain a
        /// modification timestamp for this file.
        std::optional<clocks::wall_clock::Datetime> data_modification_timestamp;
        /// Last file status-change timestamp.
        /// 
        /// If the `option` is none, the platform doesn't maintain a
        /// status-change timestamp for this file.
        std::optional<clocks::wall_clock::Datetime> status_change_timestamp;
      };
      /// When setting a timestamp, this gives the value to set it to.
      struct NewTimestamp {
        /// Leave the timestamp set to its previous value.
        struct NoChange {};
        /// Set the timestamp to the current time of the system clock associated
        /// with the filesystem.
        struct Now {};
        /// Set the timestamp to the given value.
        struct Timestamp { clocks::wall_clock::Datetime value; };
        std::variant<NoChange, Now, Timestamp> variants;
      };
      /// A directory entry.
      struct DirectoryEntry {
        /// The type of the file referred to by this directory entry.
        DescriptorType type;
        /// The name of the object.
        wit::string name;
      };
      /// Error codes returned by functions, similar to `errno` in POSIX.
      /// Not all of these error codes are returned by the functions provided by this
      /// API; some are used in higher-level library layers, and others are provided
      /// merely for alignment with POSIX.
      enum class ErrorCode : uint8_t {
        /// Permission denied, similar to `EACCES` in POSIX.
        kAccess = 0,
        /// Resource unavailable, or operation would block, similar to `EAGAIN` and `EWOULDBLOCK` in POSIX.
        kWouldBlock = 1,
        /// Connection already in progress, similar to `EALREADY` in POSIX.
        kAlready = 2,
        /// Bad descriptor, similar to `EBADF` in POSIX.
        kBadDescriptor = 3,
        /// Device or resource busy, similar to `EBUSY` in POSIX.
        kBusy = 4,
        /// Resource deadlock would occur, similar to `EDEADLK` in POSIX.
        kDeadlock = 5,
        /// Storage quota exceeded, similar to `EDQUOT` in POSIX.
        kQuota = 6,
        /// File exists, similar to `EEXIST` in POSIX.
        kExist = 7,
        /// File too large, similar to `EFBIG` in POSIX.
        kFileTooLarge = 8,
        /// Illegal byte sequence, similar to `EILSEQ` in POSIX.
        kIllegalByteSequence = 9,
        /// Operation in progress, similar to `EINPROGRESS` in POSIX.
        kInProgress = 10,
        /// Interrupted function, similar to `EINTR` in POSIX.
        kInterrupted = 11,
        /// Invalid argument, similar to `EINVAL` in POSIX.
        kInvalid = 12,
        /// I/O error, similar to `EIO` in POSIX.
        kIo = 13,
        /// Is a directory, similar to `EISDIR` in POSIX.
        kIsDirectory = 14,
        /// Too many levels of symbolic links, similar to `ELOOP` in POSIX.
        kLoop = 15,
        /// Too many links, similar to `EMLINK` in POSIX.
        kTooManyLinks = 16,
        /// Message too large, similar to `EMSGSIZE` in POSIX.
        kMessageSize = 17,
        /// Filename too long, similar to `ENAMETOOLONG` in POSIX.
        kNameTooLong = 18,
        /// No such device, similar to `ENODEV` in POSIX.
        kNoDevice = 19,
        /// No such file or directory, similar to `ENOENT` in POSIX.
        kNoEntry = 20,
        /// No locks available, similar to `ENOLCK` in POSIX.
        kNoLock = 21,
        /// Not enough space, similar to `ENOMEM` in POSIX.
        kInsufficientMemory = 22,
        /// No space left on device, similar to `ENOSPC` in POSIX.
        kInsufficientSpace = 23,
        /// Not a directory or a symbolic link to a directory, similar to `ENOTDIR` in POSIX.
        kNotDirectory = 24,
        /// Directory not empty, similar to `ENOTEMPTY` in POSIX.
        kNotEmpty = 25,
        /// State not recoverable, similar to `ENOTRECOVERABLE` in POSIX.
        kNotRecoverable = 26,
        /// Not supported, similar to `ENOTSUP` and `ENOSYS` in POSIX.
        kUnsupported = 27,
        /// Inappropriate I/O control operation, similar to `ENOTTY` in POSIX.
        kNoTty = 28,
        /// No such device or address, similar to `ENXIO` in POSIX.
        kNoSuchDevice = 29,
        /// Value too large to be stored in data type, similar to `EOVERFLOW` in POSIX.
        kOverflow = 30,
        /// Operation not permitted, similar to `EPERM` in POSIX.
        kNotPermitted = 31,
        /// Broken pipe, similar to `EPIPE` in POSIX.
        kPipe = 32,
        /// Read-only file system, similar to `EROFS` in POSIX.
        kReadOnly = 33,
        /// Invalid seek, similar to `ESPIPE` in POSIX.
        kInvalidSeek = 34,
        /// Text file busy, similar to `ETXTBSY` in POSIX.
        kTextFileBusy = 35,
        /// Cross-device link, similar to `EXDEV` in POSIX.
        kCrossDevice = 36,
      };

      /// File or memory access pattern advisory information.
      enum class Advice : uint8_t {
        /// The application has no advice to give on its behavior with respect
        /// to the specified data.
        kNormal = 0,
        /// The application expects to access the specified data sequentially
        /// from lower offsets to higher offsets.
        kSequential = 1,
        /// The application expects to access the specified data in a random
        /// order.
        kRandom = 2,
        /// The application expects to access the specified data in the near
        /// future.
        kWillNeed = 3,
        /// The application expects that it will not access the specified data
        /// in the near future.
        kDontNeed = 4,
        /// The application expects to access the specified data once and then
        /// not reuse it thereafter.
        kNoReuse = 5,
      };

      /// A 128-bit hash value, split into parts because wasm doesn't have a
      /// 128-bit integer type.
      struct MetadataHashValue {
        /// 64 bits of a 128-bit hash value.
        uint64_t lower;
        /// Another 64 bits of a 128-bit hash value.
        uint64_t upper;
      };
      class Descriptor : public wit::ResourceImportBase{

        public:

        ~Descriptor();
        std::expected<io::streams::InputStream, ErrorCode> ReadViaStream(uint64_t offset) const;
        std::expected<io::streams::OutputStream, ErrorCode> WriteViaStream(uint64_t offset) const;
        std::expected<io::streams::OutputStream, ErrorCode> AppendViaStream() const;
        std::expected<void, ErrorCode> Advise(uint64_t offset, uint64_t length, types::Advice advice) const;
        std::expected<void, ErrorCode> SyncData() const;
        std::expected<DescriptorFlags, ErrorCode> GetFlags() const;
        std::expected<DescriptorType, ErrorCode> GetType() const;
        std::expected<void, ErrorCode> SetSize(uint64_t size) const;
        std::expected<void, ErrorCode> SetTimes(types::NewTimestamp data_access_timestamp, types::NewTimestamp data_modification_timestamp) const;
        std::expected<std::tuple<wit::vector<uint8_t>, bool>, ErrorCode> Read(uint64_t length, uint64_t offset) const;
        std::expected<uint64_t, ErrorCode> Write(std::span<uint8_t const> buffer, uint64_t offset) const;
        std::expected<DirectoryEntryStream, ErrorCode> ReadDirectory() const;
        std::expected<void, ErrorCode> Sync() const;
        std::expected<void, ErrorCode> CreateDirectoryAt(std::string_view path) const;
        std::expected<DescriptorStat, ErrorCode> Stat() const;
        std::expected<DescriptorStat, ErrorCode> StatAt(types::PathFlags path_flags, std::string_view path) const;
        std::expected<void, ErrorCode> SetTimesAt(types::PathFlags path_flags, std::string_view path, types::NewTimestamp data_access_timestamp, types::NewTimestamp data_modification_timestamp) const;
        std::expected<void, ErrorCode> LinkAt(types::PathFlags old_path_flags, std::string_view old_path, std::reference_wrapper<const types::Descriptor> new_descriptor, std::string_view new_path) const;
        std::expected<Descriptor, ErrorCode> OpenAt(types::PathFlags path_flags, std::string_view path, types::OpenFlags open_flags, types::DescriptorFlags flags) const;
        std::expected<wit::string, ErrorCode> ReadlinkAt(std::string_view path) const;
        std::expected<void, ErrorCode> RemoveDirectoryAt(std::string_view path) const;
        std::expected<void, ErrorCode> RenameAt(std::string_view old_path, std::reference_wrapper<const types::Descriptor> new_descriptor, std::string_view new_path) const;
        std::expected<void, ErrorCode> SymlinkAt(std::string_view old_path, std::string_view new_path) const;
        std::expected<void, ErrorCode> UnlinkFileAt(std::string_view path) const;
        bool IsSameObject(std::reference_wrapper<const types::Descriptor> other) const;
        std::expected<MetadataHashValue, ErrorCode> MetadataHash() const;
        std::expected<MetadataHashValue, ErrorCode> MetadataHashAt(types::PathFlags path_flags, std::string_view path) const;
        Descriptor(wit::ResourceImportBase &&);
        Descriptor(Descriptor&&) = default;
        Descriptor& operator=(Descriptor&&) = default;
      };

      class DirectoryEntryStream : public wit::ResourceImportBase{

        public:

        ~DirectoryEntryStream();
        std::expected<std::optional<DirectoryEntry>, ErrorCode> ReadDirectoryEntry() const;
        DirectoryEntryStream(wit::ResourceImportBase &&);
        DirectoryEntryStream(DirectoryEntryStream&&) = default;
        DirectoryEntryStream& operator=(DirectoryEntryStream&&) = default;
      };

      std::optional<ErrorCode> FilesystemErrorCode(std::reference_wrapper<const io::error::Error> err_);
    }
    namespace preopens {
      using Descriptor = types::Descriptor;
      wit::vector<std::tuple<types::Descriptor, wit::string>> GetDirectories();
    }
  }
  namespace sockets {
    namespace network {
      class Network;
      class Network : public wit::ResourceImportBase{

        public:

        ~Network();
        Network(wit::ResourceImportBase &&);
        Network(Network&&) = default;
        Network& operator=(Network&&) = default;
      };

      /// Error codes.
      /// 
      /// In theory, every API can return any error code.
      /// In practice, API's typically only return the errors documented per API
      /// combined with a couple of errors that are always possible:
      /// - `unknown`
      /// - `access-denied`
      /// - `not-supported`
      /// - `out-of-memory`
      /// - `concurrency-conflict`
      /// 
      /// See each individual API for what the POSIX equivalents are. They sometimes differ per API.
      enum class ErrorCode : uint8_t {
        /// Unknown error
        kUnknown = 0,
        /// Access denied.
        /// 
        /// POSIX equivalent: EACCES, EPERM
        kAccessDenied = 1,
        /// The operation is not supported.
        /// 
        /// POSIX equivalent: EOPNOTSUPP
        kNotSupported = 2,
        /// One of the arguments is invalid.
        /// 
        /// POSIX equivalent: EINVAL
        kInvalidArgument = 3,
        /// Not enough memory to complete the operation.
        /// 
        /// POSIX equivalent: ENOMEM, ENOBUFS, EAI_MEMORY
        kOutOfMemory = 4,
        /// The operation timed out before it could finish completely.
        kTimeout = 5,
        /// This operation is incompatible with another asynchronous operation that is already in progress.
        /// 
        /// POSIX equivalent: EALREADY
        kConcurrencyConflict = 6,
        /// Trying to finish an asynchronous operation that:
        /// - has not been started yet, or:
        /// - was already finished by a previous `finish-*` call.
        /// 
        /// Note: this is scheduled to be removed when `future`s are natively supported.
        kNotInProgress = 7,
        /// The operation has been aborted because it could not be completed immediately.
        /// 
        /// Note: this is scheduled to be removed when `future`s are natively supported.
        kWouldBlock = 8,
        /// The operation is not valid in the socket's current state.
        kInvalidState = 9,
        /// A new socket resource could not be created because of a system limit.
        kNewSocketLimit = 10,
        /// A bind operation failed because the provided address is not an address that the `network` can bind to.
        kAddressNotBindable = 11,
        /// A bind operation failed because the provided address is already in use or because there are no ephemeral ports available.
        kAddressInUse = 12,
        /// The remote address is not reachable
        kRemoteUnreachable = 13,
        /// The TCP connection was forcefully rejected
        kConnectionRefused = 14,
        /// The TCP connection was reset.
        kConnectionReset = 15,
        /// A TCP connection was aborted.
        kConnectionAborted = 16,
        /// The size of a datagram sent to a UDP socket exceeded the maximum
        /// supported size.
        kDatagramTooLarge = 17,
        /// Name does not exist or has no suitable associated IP addresses.
        kNameUnresolvable = 18,
        /// A temporary failure in name resolution occurred.
        kTemporaryResolverFailure = 19,
        /// A permanent failure in name resolution occurred.
        kPermanentResolverFailure = 20,
      };

      enum class IpAddressFamily : uint8_t {
        /// Similar to `AF_INET` in POSIX.
        kIpv4 = 0,
        /// Similar to `AF_INET6` in POSIX.
        kIpv6 = 1,
      };

      struct IpAddress {
        struct Ipv4 { std::tuple<uint8_t, uint8_t, uint8_t, uint8_t> value; };
        struct Ipv6 { std::tuple<uint16_t, uint16_t, uint16_t, uint16_t, uint16_t, uint16_t, uint16_t, uint16_t> value; };
        std::variant<Ipv4, Ipv6> variants;
      };
      struct Ipv4SocketAddress {
        /// sin_port
        uint16_t port;
        /// sin_addr
        std::tuple<uint8_t, uint8_t, uint8_t, uint8_t> address;
      };
      struct Ipv6SocketAddress {
        /// sin6_port
        uint16_t port;
        /// sin6_flowinfo
        uint32_t flow_info;
        /// sin6_addr
        std::tuple<uint16_t, uint16_t, uint16_t, uint16_t, uint16_t, uint16_t, uint16_t, uint16_t> address;
        /// sin6_scope_id
        uint32_t scope_id;
      };
      struct IpSocketAddress {
        struct Ipv4 { network::Ipv4SocketAddress value; };
        struct Ipv6 { network::Ipv6SocketAddress value; };
        std::variant<Ipv4, Ipv6> variants;
      };
    }
    namespace instance_network {
      using Network = network::Network;
      network::Network InstanceNetwork();
    }
    namespace udp {
      class UdpSocket;
      class IncomingDatagramStream;
      class OutgoingDatagramStream;
      using Pollable = io::poll::Pollable;
      using Network = network::Network;
      using ErrorCode = network::ErrorCode;
      using IpSocketAddress = network::IpSocketAddress;
      using IpAddressFamily = network::IpAddressFamily;
      /// A received datagram.
      struct IncomingDatagram {
        /// The payload.
        /// 
        /// Theoretical max size: ~64 KiB. In practice, typically less than 1500 bytes.
        wit::vector<uint8_t> data;
        /// The source address.
        /// 
        /// This field is guaranteed to match the remote address the stream was initialized with, if any.
        /// 
        /// Equivalent to the `src_addr` out parameter of `recvfrom`.
        network::IpSocketAddress remote_address;
      };
      /// A datagram to be sent out.
      struct OutgoingDatagram {
        /// The payload.
        wit::vector<uint8_t> data;
        /// The destination address.
        /// 
        /// The requirements on this field depend on how the stream was initialized:
        /// - with a remote address: this field must be None or match the stream's remote address exactly.
        /// - without a remote address: this field is required.
        /// 
        /// If this value is None, the send operation is equivalent to `send` in POSIX. Otherwise it is equivalent to `sendto`.
        std::optional<network::IpSocketAddress> remote_address;
      };
      class UdpSocket : public wit::ResourceImportBase{

        public:

        ~UdpSocket();
        std::expected<void, network::ErrorCode> StartBind(std::reference_wrapper<const network::Network> network, network::IpSocketAddress local_address) const;
        std::expected<void, network::ErrorCode> FinishBind() const;
        std::expected<std::tuple<IncomingDatagramStream, OutgoingDatagramStream>, network::ErrorCode> Stream(std::optional<network::IpSocketAddress> remote_address) const;
        std::expected<network::IpSocketAddress, network::ErrorCode> LocalAddress() const;
        std::expected<network::IpSocketAddress, network::ErrorCode> RemoteAddress() const;
        network::IpAddressFamily AddressFamily() const;
        std::expected<uint8_t, network::ErrorCode> UnicastHopLimit() const;
        std::expected<void, network::ErrorCode> SetUnicastHopLimit(uint8_t value) const;
        std::expected<uint64_t, network::ErrorCode> ReceiveBufferSize() const;
        std::expected<void, network::ErrorCode> SetReceiveBufferSize(uint64_t value) const;
        std::expected<uint64_t, network::ErrorCode> SendBufferSize() const;
        std::expected<void, network::ErrorCode> SetSendBufferSize(uint64_t value) const;
        io::poll::Pollable Subscribe() const;
        UdpSocket(wit::ResourceImportBase &&);
        UdpSocket(UdpSocket&&) = default;
        UdpSocket& operator=(UdpSocket&&) = default;
      };

      class IncomingDatagramStream : public wit::ResourceImportBase{

        public:

        ~IncomingDatagramStream();
        std::expected<wit::vector<IncomingDatagram>, network::ErrorCode> Receive(uint64_t max_results) const;
        io::poll::Pollable Subscribe() const;
        IncomingDatagramStream(wit::ResourceImportBase &&);
        IncomingDatagramStream(IncomingDatagramStream&&) = default;
        IncomingDatagramStream& operator=(IncomingDatagramStream&&) = default;
      };

      class OutgoingDatagramStream : public wit::ResourceImportBase{

        public:

        ~OutgoingDatagramStream();
        std::expected<uint64_t, network::ErrorCode> CheckSend() const;
        std::expected<uint64_t, network::ErrorCode> Send(std::span<udp::OutgoingDatagram const> datagrams) const;
        io::poll::Pollable Subscribe() const;
        OutgoingDatagramStream(wit::ResourceImportBase &&);
        OutgoingDatagramStream(OutgoingDatagramStream&&) = default;
        OutgoingDatagramStream& operator=(OutgoingDatagramStream&&) = default;
      };

    }
    namespace udp_create_socket {
      using Network = network::Network;
      using ErrorCode = network::ErrorCode;
      using IpAddressFamily = network::IpAddressFamily;
      using UdpSocket = udp::UdpSocket;
      std::expected<udp::UdpSocket, network::ErrorCode> CreateUdpSocket(network::IpAddressFamily address_family);
    }
    namespace tcp {
      class TcpSocket;
      using InputStream = io::streams::InputStream;
      using OutputStream = io::streams::OutputStream;
      using Pollable = io::poll::Pollable;
      using Duration = uint64_t;
      using Network = network::Network;
      using ErrorCode = network::ErrorCode;
      using IpSocketAddress = network::IpSocketAddress;
      using IpAddressFamily = network::IpAddressFamily;
      enum class ShutdownType : uint8_t {
        /// Similar to `SHUT_RD` in POSIX.
        kReceive = 0,
        /// Similar to `SHUT_WR` in POSIX.
        kSend = 1,
        /// Similar to `SHUT_RDWR` in POSIX.
        kBoth = 2,
      };

      class TcpSocket : public wit::ResourceImportBase{

        public:

        ~TcpSocket();
        std::expected<void, network::ErrorCode> StartBind(std::reference_wrapper<const network::Network> network, network::IpSocketAddress local_address) const;
        std::expected<void, network::ErrorCode> FinishBind() const;
        std::expected<void, network::ErrorCode> StartConnect(std::reference_wrapper<const network::Network> network, network::IpSocketAddress remote_address) const;
        std::expected<std::tuple<io::streams::InputStream, io::streams::OutputStream>, network::ErrorCode> FinishConnect() const;
        std::expected<void, network::ErrorCode> StartListen() const;
        std::expected<void, network::ErrorCode> FinishListen() const;
        std::expected<std::tuple<TcpSocket, io::streams::InputStream, io::streams::OutputStream>, network::ErrorCode> Accept() const;
        std::expected<network::IpSocketAddress, network::ErrorCode> LocalAddress() const;
        std::expected<network::IpSocketAddress, network::ErrorCode> RemoteAddress() const;
        bool IsListening() const;
        network::IpAddressFamily AddressFamily() const;
        std::expected<void, network::ErrorCode> SetListenBacklogSize(uint64_t value) const;
        std::expected<bool, network::ErrorCode> KeepAliveEnabled() const;
        std::expected<void, network::ErrorCode> SetKeepAliveEnabled(bool value) const;
        std::expected<uint64_t, network::ErrorCode> KeepAliveIdleTime() const;
        std::expected<void, network::ErrorCode> SetKeepAliveIdleTime(uint64_t value) const;
        std::expected<uint64_t, network::ErrorCode> KeepAliveInterval() const;
        std::expected<void, network::ErrorCode> SetKeepAliveInterval(uint64_t value) const;
        std::expected<uint32_t, network::ErrorCode> KeepAliveCount() const;
        std::expected<void, network::ErrorCode> SetKeepAliveCount(uint32_t value) const;
        std::expected<uint8_t, network::ErrorCode> HopLimit() const;
        std::expected<void, network::ErrorCode> SetHopLimit(uint8_t value) const;
        std::expected<uint64_t, network::ErrorCode> ReceiveBufferSize() const;
        std::expected<void, network::ErrorCode> SetReceiveBufferSize(uint64_t value) const;
        std::expected<uint64_t, network::ErrorCode> SendBufferSize() const;
        std::expected<void, network::ErrorCode> SetSendBufferSize(uint64_t value) const;
        io::poll::Pollable Subscribe() const;
        std::expected<void, network::ErrorCode> Shutdown(tcp::ShutdownType shutdown_type) const;
        TcpSocket(wit::ResourceImportBase &&);
        TcpSocket(TcpSocket&&) = default;
        TcpSocket& operator=(TcpSocket&&) = default;
      };

    }
    namespace tcp_create_socket {
      using Network = network::Network;
      using ErrorCode = network::ErrorCode;
      using IpAddressFamily = network::IpAddressFamily;
      using TcpSocket = tcp::TcpSocket;
      std::expected<tcp::TcpSocket, network::ErrorCode> CreateTcpSocket(network::IpAddressFamily address_family);
    }
    namespace ip_name_lookup {
      class ResolveAddressStream;
      using Pollable = io::poll::Pollable;
      using Network = network::Network;
      using ErrorCode = network::ErrorCode;
      using IpAddress = network::IpAddress;
      class ResolveAddressStream : public wit::ResourceImportBase{

        public:

        ~ResolveAddressStream();
        std::expected<std::optional<network::IpAddress>, network::ErrorCode> ResolveNextAddress() const;
        io::poll::Pollable Subscribe() const;
        ResolveAddressStream(wit::ResourceImportBase &&);
        ResolveAddressStream(ResolveAddressStream&&) = default;
        ResolveAddressStream& operator=(ResolveAddressStream&&) = default;
      };

      std::expected<ResolveAddressStream, network::ErrorCode> ResolveAddresses(std::reference_wrapper<const network::Network> network, std::string_view name);
    }
  }
  namespace random {
    namespace random {
      wit::vector<uint8_t> GetRandomBytes(uint64_t len);
      uint64_t GetRandomU64();
    }
    namespace insecure {
      wit::vector<uint8_t> GetInsecureRandomBytes(uint64_t len);
      uint64_t GetInsecureRandomU64();
    }
    namespace insecure_seed {
      std::tuple<uint64_t, uint64_t> InsecureSeed();
      // export_interface Interface(Id { idx: 19 })
    }
  }
}
namespace exports {
  namespace wasi {
    namespace cli {
      namespace run {
        std::expected<void, wit::Void> Run();
      }
    }
  }
}

#endif
