package test:jco-bug;

interface handle {
    resource handle {
        constructor(path: string);
        append: func(data: string);
    }

    open-temp: func() -> own<handle>;
}

world component {
    include wasi:cli/imports@0.2.0;

    export handle;

    export wasi:cli/run@0.2.0;
}